### ISSUE TITLE
公众号香烟数据集链接错误

### ISSUE THREAD

**Issue by stan-lu** [CVUsers/Smoke-Detect-by-YoloV5#3]
你好，貌似公众号上 5k 香烟的链接给成了 烟雾3k 的链接了

**Comment by CVUsers** [comment]
复制这段内容后打开百度网盘手机App，操作更方便哦 链接:https://pan.baidu.com/s/1f_RV8nuZ416__kt5YyGTYQ 提取码:n93f------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;stan-lu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月28日(星期二) 下午5:18
收件人:&nbsp;&quot;CVUsers/Smoke-Detect-by-YoloV5&quot;<Smoke-Detect-by-YoloV5@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[CVUsers/Smoke-Detect-by-YoloV5] 公众号香烟数据集链接错误 (#3)

**Comment by stan-lu** [comment]
谢谢！
